package lense.compiler.ir;

public enum Operation {

	ADD,
	SUBTRACT,
	SYMETRIC,
	MULTIPLY,
	DIVIDE,
	REMAINDER,
	SHIFT_LEFT,
	SHIFT_RIGHT,
	LOGICAL_SHIFT_RIGHT,
	BITWISE_AND,
	BITWISE_OR,
	BITWISE_XOR,
	BITWISE_NEGATE, 
	INCREMENT, 
	DECREMENT, 
	IS_DIFFERENT_FROM, 
	IS_EQUAL_TO, 
	IS_GREATER_OR_EQUAL, 
	IS_GREATER_THAN, 
	IS_LESS_OR_EQUAL_TO, 
	IS_LESS_THAN, 
	IS_REF_DIFFERENT, 
	IS_REF_EQUAL_TO, 
	LOGICAL_SHORT_AND,
	LOGICAL_SHORT_OR
	
}
